print("Welcome To Interactive personal Data Collector")
name=input("Enter Your Name:")
age=int(input("Enter Your Age:"))
height=float(input("Enter Your Height In Meters:"))
num=int(input("Please Enter Your Favorite Number:"))
print("Thank You For Sharing Information Here  Is The Information We Have Collected.....")
print(f"Name: {name} (Type: {type(name)}), Memeory Address: {id(name)}")
print(f"Age: {age} (Type: {type(age)}), Memeory Address: {id(age)}")
print(f"Height: {height} (Type: {type(height)}), Memeory Address: {id(height)}")
print(f"Favorite Number: {num} (Type: {type(num)}), Memeory Address: {id(num)}")
print(f"Your Birth year Is Approximately {2026-age}  (based on your age of {age})")
print("Thank You For Sharing Personal Data Collector, Good Bye!")